server:
  port: 8096
#grpc:
#  port: 6565
spring:
  quartz:
    properties:
      org.quartz:
        jobStore:
          class: com.novemberain.quartz.mongodb.MongoDBJobStore
          mongoUri: mongodb://10.30.1.34:30007/bizzone_net_office?authSource=admin&directConnection=true&ssl=false
          collectionPrefix: quartz
          isClustered: true
        threadPool:
          threadCount: 5
        scheduler:
          instanceId: AUTO
          instanceName: invoices-cluster
  data:
    mongodb:
      username: ${DATABASE_USER:bizzone_crm}
      password: ${DATABASE_PASSWORD:bizzoneDEV2022}
      database: ${DATABASE_NAME:bizzone_crm}
      port: ${DATABASE_PORT:30007}
      host: ${DATABASE_HOST:10.30.1.34}
      authentication-database: admin
      auto-index-creation: true
      uuid-representation: standard
    jdbc:
      repositories:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/bizzone_id
    username: thanhha
#    username: root
    password: 013845ha
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    consumer:
      group-id: reflectoring-group

#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379
kafka:
  bootstrap-servers: localhost:9092
  topic-1: reflectoring-1
  topic-4: reflectoring-user
#logging:
#  file:
#    name: playwithgrpc.log
#    path: /home/thanhha/Documents/log/playwithgrpc.log
